"""
Crystal Symmetry utilities that implement functionality not present in AFLOW
Mainly for testing 
"""

from numpy.typing import ArrayLike
from typing import Optional,List
import logging
import numpy as np
from ase.atoms import Atoms


logger = logging.getLogger(__name__)
logging.basicConfig(filename='kim-tools.log',level=logging.INFO,force=True)

__all__ = [
    "KIMCrystal",
    "frac_pos_match_allow_permute_wrap",
    "frac_pos_match_allow_wrap",
    "atoms_frac_pos_match_allow_permute_wrap",
    "atoms_frac_pos_match_allow_wrap",
    "shuffle_atoms",
    "WYCKOFF_SETS",
    "WYCKOFF_MULTIPLICITIES"
]
            
def shuffle_atoms(
    atoms: Atoms
) -> Atoms:
    atoms_shuffled = atoms.copy()
    atoms_shuffled.set_scaled_positions(np.random.permutation(atoms.get_scaled_positions()))
    return atoms_shuffled

def _frac_pos_match_sanity_checks(
    reference_positions: ArrayLike,    
    test_positions: ArrayLike,
    reference_species: Optional[List] = None,
    test_species: Optional[List] = None,
) -> bool:
    """
    Sanity checks for comparing sets of fractional positions
    """
    if reference_species is None or test_species is None:
        if not (reference_species is None and test_species is None):
            logger.warning(
                'Refusing to compare positions when one structure has species given ' \
                'and the other does not')
            return False
        logger.info('Comparing fractional positions without species')
    else:
        if not (len(reference_positions) ==
                len(test_positions) ==
                len(reference_species) ==
                len(test_species)):
            logger.info('Atomic positions and/or species lists have different lengths between test and reference')
            return False
    
    if len(reference_positions) != len(test_positions):
        logger.info('Number of atomic positions does not match')
        return False
    return True

def frac_pos_match_allow_permute_wrap(
    reference_positions: ArrayLike,    
    test_positions: ArrayLike,
    reference_species: Optional[List] = None,
    test_species: Optional[List] = None,
) -> bool:
    """
    Check if fractional positions match allowing for permutations and PBC wrapping
    """
    if not _frac_pos_match_sanity_checks(
        reference_positions,
        test_positions,
        reference_species,
        test_species
    ):
        return False

    test_position_matched = [False]*len(test_positions)
    for i,reference_position in enumerate(reference_positions):
        for j,test_position in enumerate(test_positions):
            if test_position_matched[j]: # this position already matched. 
                continue
            position_differences = np.asarray(reference_position) - np.asarray(test_position)
            if np.allclose(position_differences,np.rint(position_differences),atol=1e-5):
                if reference_species is not None:
                    if reference_species[i] != test_species[j]:
                        logger.info(f'Reference position {i} matches test position {j} but the species do not.')
                        return False
                test_position_matched[j] = True
                break
    
    if all(test_position_matched):
        logger.info('Successfully matched the fractional positions')
        return True
    else:
        logger.info('Not all fractional positions successfully matched')
        return False

def frac_pos_match_allow_wrap(
    reference_positions: ArrayLike,    
    test_positions: ArrayLike,
    reference_species: Optional[List] = None,
    test_species: Optional[List] = None,
) -> bool:
    """
    Check if fractional positions match allowing for PBC wrapping but maintaining order
    """
    if not _frac_pos_match_sanity_checks(
        reference_positions,
        test_positions,
        reference_species,
        test_species
    ):
        return False
    
    if reference_species is not None:
        if reference_species != test_species:
            logger.info(f'Species lists do not match. Got\n{test_species}\nexpected\n{reference_species}')
            return False        
    
    for ref_pos,test_pos in zip(reference_positions, test_positions):
            position_differences = np.asarray(ref_pos) - np.asarray(test_pos)
            if not np.allclose(position_differences,np.rint(position_differences),atol=1e-5):
                logger.info(f'Failed to match positions, expected {ref_pos} got {test_pos}')
                return False
            
    logger.info('Successfully matched the fractional positions')
    return True

def atoms_frac_pos_match_allow_permute_wrap(
    reference_atoms: Atoms,
    test_atoms: Atoms
):
    return frac_pos_match_allow_permute_wrap(
        reference_atoms.get_scaled_positions(),
        test_atoms.get_scaled_positions(),
        reference_atoms.get_chemical_symbols(),
        test_atoms.get_chemical_symbols()
    )

def atoms_frac_pos_match_allow_wrap(
    reference_atoms: Atoms,
    test_atoms: Atoms
):
    return frac_pos_match_allow_wrap(
        reference_atoms.get_scaled_positions(),
        test_atoms.get_scaled_positions(),
        reference_atoms.get_chemical_symbols(),
        test_atoms.get_chemical_symbols()
    )

class KIMCrystal:
    """
    Attributes and methods of a crystal structure relevant to the KIM testing system
    
    Attributes:
        stoichiometric_species: List[str]
            List of unique species in the crystal
        prototype_label: str
            AFLOW prototype label for the crystal
        parameter_names: Optional[List[str]]
            Names of free parameters of the crystal besides 'a'. May be None if the crystal is cubic with no internal DOF.
            Should have length one less than `parameter_values_angstrom`
        parameter_values_angstrom: List[float]
            Free parameter values of the crystal. The first element in each inner list is the 'a' lattice parameter in 
            angstrom, the rest (if present) are in degrees or unitless
        library_prototype_label: Optional[str]
            AFLOW library prototype label
        short_name: Optional[List[str]]
            List of human-readable short names (e.g. "Face-Centered Cubic"), if present}
    """
    def __init__(
        prototype_label: str,
        stoichiometric_species: Optional[List[str]],
        parameter_names: Optional[List[str]],
        parameter_values_angstrom: List[float],
        library_prototype_label: Optional[str],
        short_name: Optional[List[str]],
    ):
        pass
    
WYCKOFF_SETS = {
1: ["a"],
2: ["abcdefgh", "i"],
3: ["abcd", "e"],
4: ["a"],
5: ["ab", "c"],
6: ["ab", "c"],
7: ["a"],
8: ["a", "b"],
9: ["a"],
10: ["abcdefgh", "ijkl", "mn", "o"],
11: ["abcd", "e", "f"],
12: ["abcd", "ef", "gh", "i", "j"],
13: ["abcd", "ef", "g"],
14: ["abcd", "e"],
15: ["abcd", "e", "f"],
16: ["abcdefgh", "ijklmnopqrst", "u"],
17: ["abcd", "e"],
18: ["ab", "c"],
19: ["a"],
20: ["ab", "c"],
21: ["abcd", "efgh", "ij", "k", "l"],
22: ["abcd", "efghij", "k"],
23: ["abcd", "efghij", "k"],
24: ["abc", "d"],
25: ["abcd", "efgh", "i"],
26: ["ab", "c"],
27: ["abcd", "e"],
28: ["ab", "c", "d"],
29: ["a"],
30: ["ab", "c"],
31: ["a", "b"],
32: ["ab", "c"],
33: ["a"],
34: ["ab", "c"],
35: ["ab", "c", "de", "f"],
36: ["a", "b"],
37: ["ab", "c", "d"],
38: ["ab", "c", "de", "f"],
39: ["ab", "c", "d"],
40: ["a", "b", "c"],
41: ["a", "b"],
42: ["a", "b", "cd", "e"],
43: ["a", "b"],
44: ["ab", "cd", "e"],
45: ["ab", "c"],
46: ["a", "b", "c"],
47: ["abcdefgh", "ijklmnopqrst", "uvwxyz", "A"],
48: ["abcd", "ef", "ghijkl", "m"],
49: ["abcd", "efgh", "ijkl", "mnop", "q", "r"],
50: ["abcd", "ef", "ghij", "kl", "m"],
51: ["abcd", "ef", "gh", "ij", "k", "l"],
52: ["ab", "c", "d", "e"],
53: ["abcd", "ef", "g", "h", "i"],
54: ["ab", "c", "de", "f"],
55: ["abcd", "ef", "gh", "i"],
56: ["ab", "cd", "e"],
57: ["ab", "c", "d", "e"],
58: ["abcd", "ef", "g", "h"],
59: ["ab", "cd", "ef", "g"],
60: ["ab", "c", "d"],
61: ["ab", "c"],
62: ["ab", "c", "d"],
63: ["ab", "c", "d", "e", "f", "g", "h"],
64: ["ab", "c", "d", "e", "f", "g"],
65: ["abcd", "ef", "ghij", "kl", "m", "no", "pq", "r"],
66: ["ab", "cd", "ef", "gh", "ij", "k", "l", "m"],
67: ["ab", "cdef", "g", "hijk", "l", "mn", "o"],
68: ["ab", "cd", "ef", "g", "h", "i"],
69: ["ab", "cde", "f", "ghi", "jkl", "mno", "p"],
70: ["ab", "cd", "efg", "h"],
71: ["abcd", "efghij", "k", "lmn", "o"],
72: ["ab", "cd", "e", "fg", "hi", "j", "k"],
73: ["ab", "cde", "f"],
74: ["abcd", "e", "fg", "hi", "j"],
75: ["ab", "c", "d"],
76: ["a"],
77: ["ab", "c", "d"],
78: ["a"],
79: ["a", "b", "c"],
80: ["a", "b"],
81: ["abcd", "ef", "g", "h"],
82: ["abcd", "ef", "g"],
83: ["abcd", "ef", "gh", "i", "jk", "l"],
84: ["ab", "cd", "ef", "gh", "i", "j", "k"],
85: ["ab", "c", "de", "f", "g"],
86: ["ab", "cd", "e", "f", "g"],
87: ["ab", "c", "d", "e", "f", "g", "h", "i"],
88: ["ab", "cd", "e", "f"],
89: ["abcd", "ef", "gh", "i", "jk", "lmno", "p"],
90: ["ab", "c", "d", "ef", "g"],
91: ["ab", "c", "d"],
92: ["a", "b"],
93: ["ab", "cd", "ef", "gh", "i", "jklm", "no", "p"],
94: ["ab", "c", "d", "ef", "g"],
95: ["ab", "c", "d"],
96: ["a", "b"],
97: ["ab", "c", "d", "e", "f", "g", "hi", "j", "k"],
98: ["ab", "c", "de", "f", "g"],
99: ["ab", "c", "d", "ef", "g"],
100: ["a", "b", "c", "d"],
101: ["ab", "c", "d", "e"],
102: ["a", "b", "c", "d"],
103: ["ab", "c", "d"],
104: ["a", "b", "c"],
105: ["ab", "c", "de", "f"],
106: ["a", "b", "c"],
107: ["a", "b", "c", "d", "e"],
108: ["a", "b", "c", "d"],
109: ["a", "b", "c"],
110: ["a", "b"],
111: ["abcd", "ef", "gh", "ijkl", "m", "n", "o"],
112: ["ac", "ef", "bd", "ghij", "kl", "m", "n"],
113: ["ab", "c", "d", "e", "f"],
114: ["ab", "c", "d", "e"],
115: ["abcd", "ef", "g", "hi", "jk", "l"],
116: ["ab", "cd", "ef", "gh", "i", "j"],
117: ["ab", "cd", "e", "f", "gh", "i"],
118: ["ab", "cd", "e", "fg", "h", "i"],
119: ["abcd", "ef", "gh", "i", "j"],
120: ["ad", "bc", "eh", "fg", "i"],
121: ["ab", "c", "d", "e", "fg", "h", "i", "j"],
122: ["ab", "c", "d", "e"],
123: ["abcd", "ef", "gh", "i", "jk", "lmno", "pq", "r", "st", "u"],
124: ["ac", "bd", "e", "f", "gh", "i", "j", "kl", "m", "n"],
125: ["ab", "cd", "ef", "g", "h", "ij", "kl", "m", "n"],
126: ["ab", "c", "d", "e", "f", "g", "h", "ij", "k"],
127: ["ab", "cd", "e", "f", "gh", "ij", "k", "l"],
128: ["ab", "c", "d", "e", "f", "g", "h", "i"],
129: ["ab", "c", "de", "f", "gh", "i", "j", "k"],
130: ["a", "b", "c", "d", "e", "f", "g"],
131: ["ab", "cd", "ef", "gh", "i", "jklm", "n", "op", "q", "r"],
132: ["ac", "bd", "e", "f", "gh", "k", "ij", "lm", "n", "o", "p"],
133: ["a", "b", "c", "d", "e", "f", "g", "hi", "j", "k"],
134: ["ab", "c", "d", "ef", "g", "h", "ij", "kl", "m", "n"],
135: ["a", "b", "c", "d", "e", "f", "g", "h", "i"],
136: ["ab", "c", "d", "e", "fg", "h", "i", "j", "k"],
137: ["ab", "c", "d", "e", "f", "g", "h"],
138: ["a", "b", "cd", "e", "f", "gh", "i", "j"],
139: ["ab", "c", "d", "e", "f", "g", "h", "ij", "k", "l", "m", "n", "o"],
140: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m"],
141: ["ab", "cd", "e", "f", "g", "h", "i"],
142: ["a", "b", "c", "d", "e", "f", "g"],
143: ["abc", "d"],
144: ["a"],
145: ["a"],
146: ["a", "b"],
147: ["ab", "c", "d", "ef", "g"],
148: ["ab", "c", "de", "f"],
149: ["abcdef", "ghi", "jk", "l"],
150: ["ab", "c", "d", "ef", "g"],
151: ["ab", "c"],
152: ["ab", "c"],
153: ["ab", "c"],
154: ["ab", "c"],
155: ["ab", "c", "de", "f"],
156: ["abc", "d", "e"],
157: ["a", "b", "c", "d"],
158: ["abc", "d"],
159: ["a", "b", "c"],
160: ["a", "b", "c"],
161: ["a", "b"],
162: ["ab", "cd", "e", "fg", "h", "ij", "k", "l"],
163: ["a", "b", "cd", "e", "f", "g", "h", "i"],
164: ["ab", "c", "d", "ef", "gh", "i", "j"],
165: ["a", "b", "c", "d", "e", "f", "g"],
166: ["ab", "c", "de", "fg", "h", "i"],
167: ["a", "b", "c", "d", "e", "f"],
168: ["a", "b", "c", "d"],
169: ["a"],
170: ["a"],
171: ["a", "b", "c"],
172: ["a", "b", "c"],
173: ["a", "b", "c"],
174: ["abcdef", "ghi", "jk", "l"],
175: ["ab", "cd", "e", "fg", "h", "i", "jk", "l"],
176: ["a", "b", "cd", "e", "f", "g", "h", "i"],
177: ["ab", "cd", "e", "fg", "h", "i", "jk", "lm", "n"],
178: ["a", "b", "c"],
179: ["a", "b", "c"],
180: ["ab", "cd", "e", "f", "gh", "ij", "k"],
181: ["ab", "cd", "e", "f", "gh", "ij", "k"],
182: ["a", "b", "cd", "e", "f", "g", "h", "i"],
183: ["a", "b", "c", "d", "e", "f"],
184: ["a", "b", "c", "d"],
185: ["a", "b", "c", "d"],
186: ["a", "b", "c", "d"],
187: ["abcdef", "ghi", "jk", "lm", "n", "o"],
188: ["ace", "bdf", "ghi", "j", "k", "l"],
189: ["ab", "cd", "e", "fg", "h", "i", "jk", "l"],
190: ["a", "b", "cd", "e", "f", "g", "h", "i"],
191: ["ab", "cd", "e", "fg", "h", "i", "jk", "lm", "n", "o", "pq", "r"],
192: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m"],
193: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"],
194: ["a", "b", "cd", "e", "f", "g", "h", "i", "j", "k", "l"],
195: ["ab", "cd", "e", "fi", "gh", "j"],
196: ["abcd", "e", "fg", "h"],
197: ["a", "b", "c", "d", "e", "f"],
198: ["a", "b"],
199: ["a", "b", "c"],
200: ["ab", "cd", "eh", "fg", "i", "jk", "l"],
201: ["a", "bc", "d", "e", "f", "g", "h"],
202: ["ab", "c", "d", "e", "f", "g", "h", "i"],
203: ["ab", "cd", "e", "f", "g"],
204: ["a", "b", "c", "d", "e", "f", "g", "h"],
205: ["ab", "c", "d"],
206: ["ab", "c", "d", "e"],
207: ["ab", "cd", "ef", "g", "h", "ij", "k"],
208: ["a", "bc", "d", "ef", "g", "h", "ij", "kl", "m"],
209: ["ab", "c", "d", "e", "f", "gh", "i", "j"],
210: ["ab", "cd", "e", "f", "g", "h"],
211: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
212: ["ab", "c", "d", "e"],
213: ["ab", "c", "d", "e"],
214: ["ab", "cd", "e", "f", "gh", "i"],
215: ["ab", "cd", "e", "fg", "h", "i", "j"],
216: ["abcd", "e", "fg", "h", "i"],
217: ["a", "b", "c", "d", "e", "f", "g", "h"],
218: ["a", "b", "cd", "e", "f", "gh", "i"],
219: ["ab", "cd", "e", "fg", "h"],
220: ["ab", "c", "d", "e"],
221: ["ab", "cd", "ef", "g", "h", "ij", "kl", "m", "n"],
222: ["a", "b", "c", "d", "e", "f", "g", "h", "i"],
223: ["a", "b", "cd", "e", "f", "gh", "i", "j", "k", "l"],
224: ["a", "bc", "d", "e", "f", "g", "h", "ij", "k", "l"],
225: ["ab", "c", "d", "e", "f", "g", "hi", "j", "k", "l"],
226: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
227: ["ab", "cd", "e", "f", "g", "h", "i"],
228: ["a", "b", "c", "d", "e", "f", "g", "h"],
229: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"],
230: ["a", "b", "c", "d", "e", "f", "g", "h"],
}

WYCKOFF_MULTIPLICITIES = {
    1: {
        "a": 1,
    },
    2: {
        "i": 2,
        "h": 1,
        "g": 1,
        "f": 1,
        "e": 1,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    3: {
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    4: {
        "a": 2,
    },
    5: {
        "c": 4,
        "b": 2,
        "a": 2,
    },
    6: {
        "c": 2,
        "b": 1,
        "a": 1,
    },
    7: {
        "a": 2,
    },
    8: {
        "b": 4,
        "a": 2,
    },
    9: {
        "a": 4,
    },
    10: {
        "o": 4,
        "n": 2,
        "m": 2,
        "l": 2,
        "k": 2,
        "j": 2,
        "i": 2,
        "h": 1,
        "g": 1,
        "f": 1,
        "e": 1,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    11: {
        "f": 4,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    12: {
        "j": 8,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    13: {
        "g": 4,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    14: {
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    15: {
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    16: {
        "u": 4,
        "t": 2,
        "s": 2,
        "r": 2,
        "q": 2,
        "p": 2,
        "o": 2,
        "n": 2,
        "m": 2,
        "l": 2,
        "k": 2,
        "j": 2,
        "i": 2,
        "h": 1,
        "g": 1,
        "f": 1,
        "e": 1,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    17: {
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    18: {
        "c": 4,
        "b": 2,
        "a": 2,
    },
    19: {
        "a": 4,
    },
    20: {
        "c": 8,
        "b": 4,
        "a": 4,
    },
    21: {
        "l": 8,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    22: {
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    23: {
        "k": 8,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    24: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    25: {
        "i": 4,
        "h": 2,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    26: {
        "c": 4,
        "b": 2,
        "a": 2,
    },
    27: {
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    28: {
        "d": 4,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    29: {
        "a": 4,
    },
    30: {
        "c": 4,
        "b": 2,
        "a": 2,
    },
    31: {
        "b": 4,
        "a": 2,
    },
    32: {
        "c": 4,
        "b": 2,
        "a": 2,
    },
    33: {
        "a": 4,
    },
    34: {
        "c": 4,
        "b": 2,
        "a": 2,
    },
    35: {
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    36: {
        "b": 8,
        "a": 4,
    },
    37: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    38: {
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    39: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    40: {
        "c": 8,
        "b": 4,
        "a": 4,
    },
    41: {
        "b": 8,
        "a": 4,
    },
    42: {
        "e": 16,
        "d": 8,
        "c": 8,
        "b": 8,
        "a": 4,
    },
    43: {
        "b": 16,
        "a": 8,
    },
    44: {
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    45: {
        "c": 8,
        "b": 4,
        "a": 4,
    },
    46: {
        "c": 8,
        "b": 4,
        "a": 4,
    },
    47: {
        "A": 8,
        "z": 4,
        "y": 4,
        "x": 4,
        "w": 4,
        "v": 4,
        "u": 4,
        "t": 2,
        "s": 2,
        "r": 2,
        "q": 2,
        "p": 2,
        "o": 2,
        "n": 2,
        "m": 2,
        "l": 2,
        "k": 2,
        "j": 2,
        "i": 2,
        "h": 1,
        "g": 1,
        "f": 1,
        "e": 1,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    48: {
        "m": 8,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    49: {
        "r": 8,
        "q": 4,
        "p": 4,
        "o": 4,
        "n": 4,
        "m": 4,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 2,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    50: {
        "m": 8,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    51: {
        "l": 8,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    52: {
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    53: {
        "i": 8,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    54: {
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    55: {
        "i": 8,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    56: {
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    57: {
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    58: {
        "h": 8,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    59: {
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    60: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    61: {
        "c": 8,
        "b": 4,
        "a": 4,
    },
    62: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    63: {
        "h": 16,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    64: {
        "g": 16,
        "f": 8,
        "e": 8,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    65: {
        "r": 16,
        "q": 8,
        "p": 8,
        "o": 8,
        "n": 8,
        "m": 8,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    66: {
        "m": 16,
        "l": 8,
        "k": 8,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    67: {
        "o": 16,
        "n": 8,
        "m": 8,
        "l": 8,
        "k": 8,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    68: {
        "i": 16,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    69: {
        "p": 32,
        "o": 16,
        "n": 16,
        "m": 16,
        "l": 16,
        "k": 16,
        "j": 16,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    70: {
        "h": 32,
        "g": 16,
        "f": 16,
        "e": 16,
        "d": 16,
        "c": 16,
        "b": 8,
        "a": 8,
    },
    71: {
        "o": 16,
        "n": 8,
        "m": 8,
        "l": 8,
        "k": 8,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    72: {
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    73: {
        "f": 16,
        "e": 8,
        "d": 8,
        "c": 8,
        "b": 8,
        "a": 8,
    },
    74: {
        "j": 16,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    75: {
        "d": 4,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    76: {
        "a": 4,
    },
    77: {
        "d": 4,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    78: {
        "a": 4,
    },
    79: {
        "c": 8,
        "b": 4,
        "a": 2,
    },
    80: {
        "b": 8,
        "a": 4,
    },
    81: {
        "h": 4,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    82: {
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    83: {
        "l": 8,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 2,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    84: {
        "k": 8,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    85: {
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    86: {
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    87: {
        "i": 16,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    88: {
        "f": 16,
        "e": 8,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    89: {
        "p": 8,
        "o": 4,
        "n": 4,
        "m": 4,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 2,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    90: {
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    91: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    92: {
        "b": 8,
        "a": 4,
    },
    93: {
        "p": 8,
        "o": 4,
        "n": 4,
        "m": 4,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    94: {
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    95: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    96: {
        "b": 8,
        "a": 4,
    },
    97: {
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    98: {
        "g": 16,
        "f": 8,
        "e": 8,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    99: {
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    100: {
        "d": 8,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    101: {
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    102: {
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 2,
    },
    103: {
        "d": 8,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    104: {
        "c": 8,
        "b": 4,
        "a": 2,
    },
    105: {
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    106: {
        "c": 8,
        "b": 4,
        "a": 4,
    },
    107: {
        "e": 16,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 2,
    },
    108: {
        "d": 16,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    109: {
        "c": 16,
        "b": 8,
        "a": 4,
    },
    110: {
        "b": 16,
        "a": 8,
    },
    111: {
        "o": 8,
        "n": 4,
        "m": 4,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 2,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    112: {
        "n": 8,
        "m": 4,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    113: {
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    114: {
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    115: {
        "l": 8,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    116: {
        "j": 8,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    117: {
        "i": 8,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    118: {
        "i": 8,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    119: {
        "j": 16,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    120: {
        "i": 16,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    121: {
        "j": 16,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    122: {
        "e": 16,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    123: {
        "u": 16,
        "t": 8,
        "s": 8,
        "r": 8,
        "q": 8,
        "p": 8,
        "o": 4,
        "n": 4,
        "m": 4,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 2,
        "g": 2,
        "f": 2,
        "e": 2,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    124: {
        "n": 16,
        "m": 8,
        "l": 8,
        "k": 8,
        "j": 8,
        "i": 8,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    125: {
        "n": 16,
        "m": 8,
        "l": 8,
        "k": 8,
        "j": 8,
        "i": 8,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    126: {
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    127: {
        "l": 16,
        "k": 8,
        "j": 8,
        "i": 8,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    128: {
        "i": 16,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    129: {
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    130: {
        "g": 16,
        "f": 8,
        "e": 8,
        "d": 8,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    131: {
        "r": 16,
        "q": 8,
        "p": 8,
        "o": 8,
        "n": 8,
        "m": 4,
        "l": 4,
        "k": 4,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    132: {
        "p": 16,
        "o": 8,
        "n": 8,
        "m": 8,
        "l": 8,
        "k": 8,
        "j": 4,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    133: {
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    134: {
        "n": 16,
        "m": 8,
        "l": 8,
        "k": 8,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    135: {
        "i": 16,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    136: {
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 4,
        "f": 4,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    137: {
        "h": 16,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    138: {
        "j": 16,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    139: {
        "o": 32,
        "n": 16,
        "m": 16,
        "l": 16,
        "k": 16,
        "j": 8,
        "i": 8,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    140: {
        "m": 32,
        "l": 16,
        "k": 16,
        "j": 16,
        "i": 16,
        "h": 8,
        "g": 8,
        "f": 8,
        "e": 8,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    141: {
        "i": 32,
        "h": 16,
        "g": 16,
        "f": 16,
        "e": 8,
        "d": 8,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    142: {
        "g": 32,
        "f": 16,
        "e": 16,
        "d": 16,
        "c": 16,
        "b": 8,
        "a": 8,
    },
    143: {
        "d": 3,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    144: {
        "a": 3,
    },
    145: {
        "a": 3,
    },
    146: {
        "b": 9,
        "a": 3,
    },
    147: {
        "g": 6,
        "f": 3,
        "e": 3,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    148: {
        "f": 18,
        "e": 9,
        "d": 9,
        "c": 6,
        "b": 3,
        "a": 3,
    },
    149: {
        "l": 6,
        "k": 3,
        "j": 3,
        "i": 2,
        "h": 2,
        "g": 2,
        "f": 1,
        "e": 1,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    150: {
        "g": 6,
        "f": 3,
        "e": 3,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    151: {
        "c": 6,
        "b": 3,
        "a": 3,
    },
    152: {
        "c": 6,
        "b": 3,
        "a": 3,
    },
    153: {
        "c": 6,
        "b": 3,
        "a": 3,
    },
    154: {
        "c": 6,
        "b": 3,
        "a": 3,
    },
    155: {
        "f": 18,
        "e": 9,
        "d": 9,
        "c": 6,
        "b": 3,
        "a": 3,
    },
    156: {
        "e": 6,
        "d": 3,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    157: {
        "d": 6,
        "c": 3,
        "b": 2,
        "a": 1,
    },
    158: {
        "d": 6,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    159: {
        "c": 6,
        "b": 2,
        "a": 2,
    },
    160: {
        "c": 18,
        "b": 9,
        "a": 3,
    },
    161: {
        "b": 18,
        "a": 6,
    },
    162: {
        "l": 12,
        "k": 6,
        "j": 6,
        "i": 6,
        "h": 4,
        "g": 3,
        "f": 3,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    163: {
        "i": 12,
        "h": 6,
        "g": 6,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    164: {
        "j": 12,
        "i": 6,
        "h": 6,
        "g": 6,
        "f": 3,
        "e": 3,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    165: {
        "g": 12,
        "f": 6,
        "e": 6,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    166: {
        "i": 36,
        "h": 18,
        "g": 18,
        "f": 18,
        "e": 9,
        "d": 9,
        "c": 6,
        "b": 3,
        "a": 3,
    },
    167: {
        "f": 36,
        "e": 18,
        "d": 18,
        "c": 12,
        "b": 6,
        "a": 6,
    },
    168: {
        "d": 6,
        "c": 3,
        "b": 2,
        "a": 1,
    },
    169: {
        "a": 6,
    },
    170: {
        "a": 6,
    },
    171: {
        "c": 6,
        "b": 3,
        "a": 3,
    },
    172: {
        "c": 6,
        "b": 3,
        "a": 3,
    },
    173: {
        "c": 6,
        "b": 2,
        "a": 2,
    },
    174: {
        "l": 6,
        "k": 3,
        "j": 3,
        "i": 2,
        "h": 2,
        "g": 2,
        "f": 1,
        "e": 1,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    175: {
        "l": 12,
        "k": 6,
        "j": 6,
        "i": 6,
        "h": 4,
        "g": 3,
        "f": 3,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    176: {
        "i": 12,
        "h": 6,
        "g": 6,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    177: {
        "n": 12,
        "m": 6,
        "l": 6,
        "k": 6,
        "j": 6,
        "i": 6,
        "h": 4,
        "g": 3,
        "f": 3,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    178: {
        "c": 12,
        "b": 6,
        "a": 6,
    },
    179: {
        "c": 12,
        "b": 6,
        "a": 6,
    },
    180: {
        "k": 12,
        "j": 6,
        "i": 6,
        "h": 6,
        "g": 6,
        "f": 6,
        "e": 6,
        "d": 3,
        "c": 3,
        "b": 3,
        "a": 3,
    },
    181: {
        "k": 12,
        "j": 6,
        "i": 6,
        "h": 6,
        "g": 6,
        "f": 6,
        "e": 6,
        "d": 3,
        "c": 3,
        "b": 3,
        "a": 3,
    },
    182: {
        "i": 12,
        "h": 6,
        "g": 6,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    183: {
        "f": 12,
        "e": 6,
        "d": 6,
        "c": 3,
        "b": 2,
        "a": 1,
    },
    184: {
        "d": 12,
        "c": 6,
        "b": 4,
        "a": 2,
    },
    185: {
        "d": 12,
        "c": 6,
        "b": 4,
        "a": 2,
    },
    186: {
        "d": 12,
        "c": 6,
        "b": 2,
        "a": 2,
    },
    187: {
        "o": 12,
        "n": 6,
        "m": 6,
        "l": 6,
        "k": 3,
        "j": 3,
        "i": 2,
        "h": 2,
        "g": 2,
        "f": 1,
        "e": 1,
        "d": 1,
        "c": 1,
        "b": 1,
        "a": 1,
    },
    188: {
        "l": 12,
        "k": 6,
        "j": 6,
        "i": 4,
        "h": 4,
        "g": 4,
        "f": 2,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    189: {
        "l": 12,
        "k": 6,
        "j": 6,
        "i": 6,
        "h": 4,
        "g": 3,
        "f": 3,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    190: {
        "i": 12,
        "h": 6,
        "g": 6,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    191: {
        "r": 24,
        "q": 12,
        "p": 12,
        "o": 12,
        "n": 12,
        "m": 6,
        "l": 6,
        "k": 6,
        "j": 6,
        "i": 6,
        "h": 4,
        "g": 3,
        "f": 3,
        "e": 2,
        "d": 2,
        "c": 2,
        "b": 1,
        "a": 1,
    },
    192: {
        "m": 24,
        "l": 12,
        "k": 12,
        "j": 12,
        "i": 12,
        "h": 8,
        "g": 6,
        "f": 6,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    193: {
        "l": 24,
        "k": 12,
        "j": 12,
        "i": 12,
        "h": 8,
        "g": 6,
        "f": 6,
        "e": 4,
        "d": 4,
        "c": 4,
        "b": 2,
        "a": 2,
    },
    194: {
        "l": 24,
        "k": 12,
        "j": 12,
        "i": 12,
        "h": 6,
        "g": 6,
        "f": 4,
        "e": 4,
        "d": 2,
        "c": 2,
        "b": 2,
        "a": 2,
    },
    195: {
        "j": 12,
        "i": 6,
        "h": 6,
        "g": 6,
        "f": 6,
        "e": 4,
        "d": 3,
        "c": 3,
        "b": 1,
        "a": 1,
    },
    196: {
        "h": 48,
        "g": 24,
        "f": 24,
        "e": 16,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    197: {
        "f": 24,
        "e": 12,
        "d": 12,
        "c": 8,
        "b": 6,
        "a": 2,
    },
    198: {
        "b": 12,
        "a": 4,
    },
    199: {
        "c": 24,
        "b": 12,
        "a": 8,
    },
    200: {
        "l": 24,
        "k": 12,
        "j": 12,
        "i": 8,
        "h": 6,
        "g": 6,
        "f": 6,
        "e": 6,
        "d": 3,
        "c": 3,
        "b": 1,
        "a": 1,
    },
    201: {
        "h": 24,
        "g": 12,
        "f": 12,
        "e": 8,
        "d": 6,
        "c": 4,
        "b": 4,
        "a": 2,
    },
    202: {
        "i": 96,
        "h": 48,
        "g": 48,
        "f": 32,
        "e": 24,
        "d": 24,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    203: {
        "g": 96,
        "f": 48,
        "e": 32,
        "d": 16,
        "c": 16,
        "b": 8,
        "a": 8,
    },
    204: {
        "h": 48,
        "g": 24,
        "f": 16,
        "e": 12,
        "d": 12,
        "c": 8,
        "b": 6,
        "a": 2,
    },
    205: {
        "d": 24,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    206: {
        "e": 48,
        "d": 24,
        "c": 16,
        "b": 8,
        "a": 8,
    },
    207: {
        "k": 24,
        "j": 12,
        "i": 12,
        "h": 12,
        "g": 8,
        "f": 6,
        "e": 6,
        "d": 3,
        "c": 3,
        "b": 1,
        "a": 1,
    },
    208: {
        "m": 24,
        "l": 12,
        "k": 12,
        "j": 12,
        "i": 12,
        "h": 12,
        "g": 8,
        "f": 6,
        "e": 6,
        "d": 6,
        "c": 4,
        "b": 4,
        "a": 2,
    },
    209: {
        "j": 96,
        "i": 48,
        "h": 48,
        "g": 48,
        "f": 32,
        "e": 24,
        "d": 24,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    210: {
        "h": 96,
        "g": 48,
        "f": 48,
        "e": 32,
        "d": 16,
        "c": 16,
        "b": 8,
        "a": 8,
    },
    211: {
        "j": 48,
        "i": 24,
        "h": 24,
        "g": 24,
        "f": 16,
        "e": 12,
        "d": 12,
        "c": 8,
        "b": 6,
        "a": 2,
    },
    212: {
        "e": 24,
        "d": 12,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    213: {
        "e": 24,
        "d": 12,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    214: {
        "i": 48,
        "h": 24,
        "g": 24,
        "f": 24,
        "e": 16,
        "d": 12,
        "c": 12,
        "b": 8,
        "a": 8,
    },
    215: {
        "j": 24,
        "i": 12,
        "h": 12,
        "g": 6,
        "f": 6,
        "e": 4,
        "d": 3,
        "c": 3,
        "b": 1,
        "a": 1,
    },
    216: {
        "i": 96,
        "h": 48,
        "g": 24,
        "f": 24,
        "e": 16,
        "d": 4,
        "c": 4,
        "b": 4,
        "a": 4,
    },
    217: {
        "h": 48,
        "g": 24,
        "f": 24,
        "e": 12,
        "d": 12,
        "c": 8,
        "b": 6,
        "a": 2,
    },
    218: {
        "i": 24,
        "h": 12,
        "g": 12,
        "f": 12,
        "e": 8,
        "d": 6,
        "c": 6,
        "b": 6,
        "a": 2,
    },
    219: {
        "h": 96,
        "g": 48,
        "f": 48,
        "e": 32,
        "d": 24,
        "c": 24,
        "b": 8,
        "a": 8,
    },
    220: {
        "e": 48,
        "d": 24,
        "c": 16,
        "b": 12,
        "a": 12,
    },
    221: {
        "n": 48,
        "m": 24,
        "l": 24,
        "k": 24,
        "j": 12,
        "i": 12,
        "h": 12,
        "g": 8,
        "f": 6,
        "e": 6,
        "d": 3,
        "c": 3,
        "b": 1,
        "a": 1,
    },
    222: {
        "i": 48,
        "h": 24,
        "g": 24,
        "f": 16,
        "e": 12,
        "d": 12,
        "c": 8,
        "b": 6,
        "a": 2,
    },
    223: {
        "l": 48,
        "k": 24,
        "j": 24,
        "i": 16,
        "h": 12,
        "g": 12,
        "f": 12,
        "e": 8,
        "d": 6,
        "c": 6,
        "b": 6,
        "a": 2,
    },
    224: {
        "l": 48,
        "k": 24,
        "j": 24,
        "i": 24,
        "h": 24,
        "g": 12,
        "f": 12,
        "e": 8,
        "d": 6,
        "c": 4,
        "b": 4,
        "a": 2,
    },
    225: {
        "l": 192,
        "k": 96,
        "j": 96,
        "i": 48,
        "h": 48,
        "g": 48,
        "f": 32,
        "e": 24,
        "d": 24,
        "c": 8,
        "b": 4,
        "a": 4,
    },
    226: {
        "j": 192,
        "i": 96,
        "h": 96,
        "g": 64,
        "f": 48,
        "e": 48,
        "d": 24,
        "c": 24,
        "b": 8,
        "a": 8,
    },
    227: {
        "i": 192,
        "h": 96,
        "g": 96,
        "f": 48,
        "e": 32,
        "d": 16,
        "c": 16,
        "b": 8,
        "a": 8,
    },
    228: {
        "h": 192,
        "g": 96,
        "f": 96,
        "e": 64,
        "d": 48,
        "c": 32,
        "b": 32,
        "a": 16,
    },
    229: {
        "l": 96,
        "k": 48,
        "j": 48,
        "i": 48,
        "h": 24,
        "g": 24,
        "f": 16,
        "e": 12,
        "d": 12,
        "c": 8,
        "b": 6,
        "a": 2,
    },
    230: {
        "h": 96,
        "g": 48,
        "f": 48,
        "e": 32,
        "d": 24,
        "c": 24,
        "b": 16,
        "a": 16,
    },
}