name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1.12
  send-pull-request-to-kdp:
    uses: openkim/reusable-workflows/.github/workflows/upversion-pypi-package-and-send-pr.yml@main
    secrets: inherit
    with:
      target-repository: developer-platform
      target-repository-base-branch: main
      recipe-file-path: docker/install/Dockerfile
    needs: deploy
  send-pull-request-to-pipeline:
    uses: openkim/reusable-workflows/.github/workflows/upversion-pypi-package-and-send-pr.yml@main
    secrets: inherit
    with:
      target-repository: openkim-pipeline
      target-repository-base-branch: devel
      recipe-file-path: singularity/hpccm-recipe-cumulative.py
    needs: deploy
